/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    BillTable: typeof import('./components/BillTable.vue')['default']
    CalculatePanel: typeof import('./components/CalculatePanel.vue')['default']
    FakeLogin: typeof import('./components/FakeLogin.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    MealCard: typeof import('./components/MealCard.vue')['default']
    MealCardList: typeof import('./components/MealCardList.vue')['default']
    MealOrders: typeof import('./components/MealOrders.vue')['default']
    NewMealDialog: typeof import('./components/NewMealDialog.vue')['default']
    NewOrderDialog: typeof import('./components/NewOrderDialog.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
